### ISSUE TITLE
[Feature Request]Ability to edit an incident

### ISSUE THREAD

**Issue by itsfolf** [eladnava/cachet-api#1]
You should be able to edit an incident status and message, since otherwise the unique way to set your component back to online is manually going to the dashboard.

**Comment by eladnava** [comment]
Hi @checkium, thanks for your suggestion.

I think publishing a new incident with a **Fixed** component status appears to be the "Cachet" way to do it.

This makes more sense because people who visit the status page will be able to understand when the incident started and how long it took to resolve. If you edit the original incident, that information cannot be derived.

**Comment by itsfolf** [comment]
@eladnava Oh, I didn't think about that.
